### ISSUE TITLE
Upgrade to version 0.10.1

### ISSUE THREAD

**Issue by holyjak** [aws-observability/aws-otel-java-instrumentation#10]
Are there plans to upgrade to open-telemetry agent v. 0.10.1 anytime soon? I need it to fix open-telemetry/opentelemetry-java/#2052 Thank you!

**Comment by anuraaga** [comment]
Hey - thanks for checking in. We'll get this released shortly!

**Comment by anuraaga** [comment]
@holyjak Thanks for the patience! 0.10.1 has been [released](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/tag/v0.10.1-aws.1)
