### ISSUE TITLE
No trace_id in logs with log4j2 + Spring Boot

### ISSUE THREAD

**Issue by saefty** [aws-observability/aws-otel-java-instrumentation#100]
**Describe the bug**
The trace_id, span_id and trace_flags are not logged with log4j2 + spring boot.

With the javaagent provided from this repository (1.6.0)
- log4j2: no logging context set at all
- logback: log context set properly

With the javaagent from open-telemetry (1.6.2)
- log4j2: logging in place
- logback: logging in place

**Steps to reproduce**
[Here](https://github.com/saefty/otel-spring-boot-example) is a repository that reproduces the described issue.
_Note, there are no tests in the repository. But the application logs show the faulty behaviour._

**What did you expect to see?**
- The aws otel javaagent should behave the same way as it does with the original distribution.

**What did you see instead?**
- The aws otel javaagent is unable to set the correct log4j2 context.

**Additional context**
The same application works when using the [native javaagent](https://github.com/open-telemetry/opentelemetry-java-instrumentation) from the open-telemetry org.
![image](https://user-images.githubusercontent.com/25341735/137726354-ba489c4b-2b09-4354-852a-b3f38340e131.png)
[gradle-q-dependencis.txt](https://github.com/aws-observability/aws-otel-java-instrumentation/files/7364612/gradle-q-dependencis.txt)

**Comment by anuraaga** [comment]
@willarmiros Yeah think so - sorry for the delay, sent a fix in #102

**Comment by caoheyang** [comment]
Hey, everyone,

When I used Spring Boot 2.1.9.RELEASE, this bug recurrent.

So,excuse me, does this have anything to do with the Spring boot version? Because I can get trace_id in Spring boot 2.2.6.

Regards & Thanks.

Heyang
