### ISSUE TITLE
Create release to patch critical log4j security issue

### ISSUE THREAD

**Issue by leosobral** [aws-observability/aws-otel-java-instrumentation#129]
The log4j dependency has a critical security vulnerability: https://www.kaspersky.com/blog/log4shell-critical-vulnerability-in-apache-log4j/43124/

The latest commit in master fixes this by updating the log4j dependency to > 2.15.

Can you create a release to include the critical security fix, so we don't need to build a separate jar from master?

**Comment by anuraaga** [comment]
Hi @leosobral - this distribution does not include log4j in user-facing artifacts, it only uses it in smoke tests. log4j is provided by the app, if it's not there, instrumentation is not applied - the agent does not bring in any particular version of it. Similar detail can be found at https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4904
