### ISSUE TITLE
Soak Tests fail to build image when multiple platforms are targetted

### ISSUE THREAD

**Issue by NathanielRN** [aws-observability/aws-otel-java-instrumentation#145]
**Describe the bug**
A few days ago when #144 was merged, the daily [Soak Tests started failing ](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/1724041906)with the following message:

```
Soak Performance Test - (springboot, auto)
Execution failed for task ':sample-apps:spark:jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: multi-platform image building not supported when pushing to Docker engine
```

I'm especially curious why it is executing a `spark` task on the `springboot` test? I guess the tests have always built every Docker Image on every matrix job? I guess this is because the `main-build` doesn't build them separately, but let me know if this is not the best way to be doing this?

In #144 we added this code which the error message seems to be referring to:

https://github.com/aws-observability/aws-otel-java-instrumentation/blob/891a9f603414b0d02028ee21a4ce392015f352c8/otelagent/build.gradle.kts#L129-L138

**Steps to reproduce**
See the [Soak Testing Actions Page](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/soak-testing.yml).

**What did you expect to see?**
Regular successful operation.

**What did you see instead?**
Failure to build the Docker Image.

**Additional context**

I noticed that the way the Main Build (which is passing successfully) and the way the Soak Test builds the Docker Images is different:

Main Build:

https://github.com/aws-observability/aws-otel-java-instrumentation/blob/891a9f603414b0d02028ee21a4ce392015f352c8/.github/workflows/main-build.yml#L32-L40

Soak Tests:

https://github.com/aws-observability/aws-otel-java-instrumentation/blob/891a9f603414b0d02028ee21a4ce392015f352c8/.github/workflows/soak-testing.yml#L112-L117

Maybe if the Soak Tests are just made to match the Main Build then the tests will pass again?

Please let me know if that makes sense and I can make a PR to do this change!

**Comment by NathanielRN** [comment]
@anuraaga Would appreciate your opinion on if you think moving to the `main-build` format of building the apps would be the right move! 🙂

**Comment by anuraaga** [comment]
@NathanielRN `main-build` builds and pushes while the soak tests intentionally don't push. Unfortunately jib (nor docker buildx itself) support multiplatform builds to a local docker. One workaround would be to add a flag to disable the multiplatform build for the soak tests, the other could be starting a local docker registry in the github runner. But we are moving in the direction of removing soak tests, and removed them already for collector, this is probably good impetus to potentially do the same here. We can either run performance tests on each main build commit or delete them in favor of focusing on [upstream](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/benchmark-overhead). Will bring up with the team.
