### ISSUE TITLE
Add ability to use generate XRAY traceId without spanId in log context

### ISSUE THREAD

**Issue by gautam-nutalapati** [aws-observability/aws-otel-java-instrumentation#151]
**Is your feature request related to a problem? Please describe.**
Using spanId as part of XRAY traceId makes the injected `AWS-XRAY-TRACE-ID` to be different for every micro-service logs.
While we can search logs using wild card pattern, this feature enables us to remove unnecessary log data which is not preferable by everyone.

**Describe the solution you'd like**
Library uses environment variable `XRAY-TRACE-ID-WITH-SPAN` to have below behavior:
- When this is set to true, spanId is used for `AWS-XRAY-TRACE-ID`
- When this is set to false, spanId is not used for `AWS-XRAY-TRACE-ID`
- When this environment variable is not set, default behavior stays the same (spanId is used for `AWS-XRAY-TRACE-ID`)

**Comment by anuraaga** [comment]
Hi @gautam-nutalapati - the `AWS-XRAY-TRACE-ID` is specially formatted for use with AWS service lens and similar features. If you only want the trace ID to be able to search in logs, are you able to use the normal OpenTelemetry instrumentation and the `trace_id` context attribute?

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/f7da97bd9d06ae2ec1d2c56a8c7e36a9540c0861/instrumentation/logback/logback-mdc-1.0/library/README.md

**Comment by gautam-nutalapati** [comment]
I am hoping to return traceId in response header, and search logs and Xray with the same traceId.
When using `AWS-XRAY-TRACE-ID` logger context, XRAY traceId I see in the logs is `1-61f88b31-a611ce43ce0bb03ea167d942@4e8cd197dc2f7d54`.
But in Xray console, I see `1-61f88b31-a611ce43ce0bb03ea167d942` is the traceId.

Can we ensure we are using the exact traceId in logger context as the traceId that's seen in XRAY?
Use of spanId in `AWS-XRAY-TRACE-ID` logger context seems unrelated to format required by AWS service, as we can print anything in the logs.

Our alternate option would be to use [this](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/500699390e138476afbbd52e39a78b63abf4da53/instrumentation/log4j-2.13.2/src/main/java/software/amazon/opentelemetry/javaagent/instrumentation/log4j_2_13_2/AwsXrayContextDataProvider.java#L39) logic in our own code, but I would prefer the change made in library itself if its a common use case.

**Comment by anuraaga** [comment]
`AWS-XRAY-TRACE-ID` isn't a very good name for legacy reasons, it's similar to the `X-Amzn-Trace-Id` header which includes both trace and span information. `AWS-XRAY-TRACE-ID` is specifically to support service lens, it needs the span ID so you can e.g., jump from a span to the logs for that span.

It might also be helpful to allow outputing trace ID by itself though I'm not too sure. @willarmiros can you take a look at this?

**Comment by willarmiros** [comment]
> I am hoping to return traceId in response header, and search logs and Xray with the same traceId

Hmmm this is possible, as stated if you just ignore the spanId after the `@` symbol. I'm not sure if this would be a common enough use case to justify an env var for it - I don't think many users would opt-in to *less* data being output. 


As an FYI, the `AWS-XRAY-TRACE-ID` prefix is not necessary for ServiceLens to work, so we can make that configurable as we did [in the X-Ray SDK](https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-java-configuration.html#xray-sdk-java-configuration-logging), but I don't think that's what this feature request is for at least.

**Comment by gautam-nutalapati** [comment]
Thank you for the responses!
Sounds like this may not be implemented as it may not be a popular demand. Hence closing this.
