### ISSUE TITLE
AWS XRay service map components are disconnected

### ISSUE THREAD

**Issue by Heeminkim87** [aws-observability/aws-otel-java-instrumentation#153]
hello my project used aws x-ray
and we used otel collector and used java agent

1month ago ,
service map can see connected each components
but recently
service map components are disconnected

and when i check trace Parent ID was null
like this
https://i.stack.imgur.com/qzduR.png

my project info is here

sidecar [task definition]
public.ecr.aws/aws-observability/aws-otel-collector:latest
["--config","/etc/ecs/ecs-default-config.yaml"]

application Docker
ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar /opt/aws-opentelemetry-agent.jar
ENV JAVA_TOOL_OPTIONS=-javaagent:/opt/aws-opentelemetry-agent.jar
ENV OTEL_RESOURCE_ATTRIBUTES=service.name={servicename}

java -javaagent:/opt/aws-opentelemetry-agent.jar -jar -Dotel.instrumentation.common.default-enabled=true
-Dotel.instrumentation.opentelemetry-annotations.enabled=true

i need help.
could u tell me any proper solution?

thanks

**Comment by willarmiros** [comment]
Hi @Heeminkim87,

Thank you for raising this issue. Do you know what version of the Java agent you are using? If you recently upgraded, do you know what version you were using? If you don't know, could you share a raw trace JSON for each of the disconnected services?

@anuraaga this looks like it may be a regression with the propagator. Could you take a look?

**Comment by anuraaga** [comment]
Hi @Heeminkim87 - are you using Kafka? I think you need to add this flag for it to work

`-Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true`

https://github.com/open-telemetry/opentelemetry-java-instrumentation/discussions/4509
