### ISSUE TITLE
AWS-XRAY-TRACE-ID in logs is invalid in Kafka Consumer

### ISSUE THREAD

**Issue by sukrit007wawa** [aws-observability/aws-otel-java-instrumentation#155]
**Describe the bug**
The value of context: AWS-XRAY-TRACE-ID in log back MDC when using Kafka consumer includes additional span information.  As a result of this,  the logs of consumers do not show up in Cloudwatch XRay Servicelens

**Steps to reproduce**
Configure Spring Cloud Stream consumer and producer application that leverages logback with console appender: 
`
<?xml version="1.0" encoding="UTF-8"?>
<configuration>

    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg - trace_id=%X{AWS-XRAY-TRACE-ID} span_id=%X{span_id}%n</pattern>
        </encoder>
    </appender>

    <root level="INFO">
        <appender-ref ref="CONSOLE" />
    </root>

</configuration>
`

**What did you expect to see?**
Expected value in logs:  1-620c8c8e-086e6bac61ca8dd17818b407

**What did you see instead?**
`05:47:02.118 [KafkaConsumerDestination{consumerDestinationName='healthCheckTopic', partitions=3, dlqName='null'}.container-0-C-1] INFO  c.w.m.s.StreamKafkaMessageConsumer - Message: 2022:02:16:05:47:02 - trace_id=1-620c8fd6-58fd61a043994fc302bd6d9f@895c47ebc8e3f9b7 span_id=895c47ebc8e3f9b7`

Actual value in logs:       1-620c8c8e-086e6bac61ca8dd17818b407@fad4e1b1e2bc0519

**Additional context**
ADOT Autoinstrumentation:  1.10.1
ADOT Collector:  0.16.0

**Comment by anuraaga** [comment]
Hi @sukrit007wawa - `1-620c8c8e-086e6bac61ca8dd17818b407@fad4e1b1e2bc0519` is the correct format for service lens (X-Ray uses the word "trace ID" confusingly to include a span ID as well when it comes to propagation). If it's not working, there is probably another issue, possibly related to setting resource attributes to the log stream name. /cc @willarmiros

**Comment by willarmiros** [comment]
Yep, specifically `aws.log.group.names` attribute must be populated in at least 1 span on the trace pointing to the appropriate CW Log group for ServiceLens correlation to work

**Comment by sukrit007wawa** [comment]
We figured out the issue of why logs were not showing up.  There was a delay from cloudwatch agent.  Looks like Service Lens excludes span id when it tries to query:  filter @message like "1-620c8c8e-086e6bac61ca8dd17818b407" which should include span ids as well.    We can close this issue.   THanks!
