### ISSUE TITLE
service.name not being honored for spans created within Java application

### ISSUE THREAD

**Issue by justinfiore** [aws-observability/aws-otel-java-instrumentation#158]
**Describe the bug**
We are creating spans within our Java application like:
```
Span span = tracer.spanBuilder("abc").startSpan();
```
When these spans are created, the "service name" is the span name rather than the value of the `service.name` which is configured either using the environment variable `OTEL_SERVICE_NAME` or via environment variable `OTEL_RESOURCE_ATTRIBUTES=service.name=myservice`

**Steps to reproduce**
Using `aws-opentelemetry-agent.jar` version `1.7.1`

**What did you expect to see?**
I expected to see the service name "myservice" in all spans produced by this service in AWS X-Ray.

**What did you see instead?**
Instead the service name appears as the Span name for most spans.

**Additional context**
I have tried both using `OTEL_SERVICE_NAME=myservice` and `OTEL_RESOURCE_ATTRIBUTES=service.name=myservice`
The service name is correct in other tools like Jaeger and Grafana Tempo

**Comment by awsimaya** [comment]
@willarmiros , can you please take a look at this issue?

**Comment by willarmiros** [comment]
Hello,

This seems similar to https://github.com/aws-observability/aws-otel-collector/issues/894. We are aware of this issue and have it on our priority list to fix. Basically, the `service.name` should always be respected if set and if no more appropriate naming options are there.

**Comment by eramos-ce** [comment]
Is `service.name` equivalent to `otel.service.name`?

**Comment by nerudadhich** [comment]
Hi, Team. We are also same issue, is there any workaround or any progress made on this ?

**Comment by colin-humphrey** [comment]
This would definitely improve the product., is this prioritised and on the roadmap?
