### ISSUE TITLE
Tracing stopped working in Java Application

### ISSUE THREAD

**Issue by rasik-sheth** [aws-observability/aws-otel-java-instrumentation#171]
We have Springboot based application running on AWS.
- Springboot
- Java Coerretto 11
- Running on AWS in docker

We are using https://github.com/aws-observability/aws-otel-java-instrumentation agent to collect the metrics and traces and to publish it to AWS prometheus. 

From version 1.13, we have observed that while metrics worked, the trace stopped working. We were able to confirm the behavior by replacing 1.13 with 1.12 version of the jar.

Are there any known issues with 1.13.0 release?

**Comment by bryan-aguilar** [comment]
Thank you for the report, we will take a look at this issue.

**Comment by vasireddy99** [comment]
Hi @rasik-sheth, can you please try with latest release  [ADOT Java Agent v1.16.0](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/tag/v1.16.0) and if you are still facing this issue, please attach logs by using logging exporter with `loglevel: debug` for more context.

**Comment by vasireddy99** [comment]
Adding more information. The Traces are generated with spring boot sample app using ADOT Java Agent 1.13+ version and validated in the [tests](https://github.com/aws-observability/aws-otel-java-instrumentation/actions/runs/3100616376/jobs/5021129358#step:6:704). 

Example spring boot sample app: https://github.com/aws-observability/aws-otel-java-instrumentation/tree/main/sample-apps/springboot

Closing this issue as inactive from past 2 months. Please re-open if you are still facing the issues.
