### ISSUE TITLE
Provide options to disable AWS resource detection for on-premise applications

### ISSUE THREAD

**Issue by cloudnativestack** [aws-observability/aws-otel-java-instrumentation#181]
**Is your feature request related to a problem? Please describe.**
With auto-instrumentation with the aws-otel java agent, the agent will try to connect to 169.254.169.254 in order to retrieve information about current environment. This is default and OK behavior for applications running in AWS environment. However, for on-premise applications, the connection will time out and retry and time out again until max times of failures reached. This will incur a super long start up latency, roughly about 2 to 2.5 minutes.

**Describe the solution you'd like**
Please provide a option to disable the resource detector, such as providing environment variables, program arguments.

**Comment by strivingdevs** [comment]
Hi, the upstream already provided an environment variable: OTEL_JAVA_DISABLED_RESOURCE_PROVIDERS

However, there is no name documented for AWS resource provider

**Comment by strivingdevs** [comment]
Gentle bump to avoid automatic closing without answer

**Comment by rapphil** [comment]
Hi I will take a look and check the documentation.

**Comment by rapphil** [comment]
The list of resource providers that can be disabled with the `OTEL_JAVA_DISABLED_RESOURCE_PROVIDERS` is here: https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/aws/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider

There is a link for that list from this page: https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#resource-provider-spi

**Comment by rapphil** [comment]
As of ADOT Java Agent 1.21.0, this is the list of resource providers: https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-resources/src/main/resources/META-INF/services/io.opentelemetry.sdk.autoconfigure.spi.ResourceProvider

For more information, please refer to: 
https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#disabling-automatic-resourceproviders
