### ISSUE TITLE
How to create tracer instance for manual span creation in auto-instrumented app?

### ISSUE THREAD

**Issue by syr** [aws-observability/aws-otel-java-instrumentation#183]
I have a quarkus app with auto-instrumentation by [aws-opentelemetry-agent.jar](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar)

Tried to get a tracer for manuel span creation by inject io.opentelemetry.api.OpenTelemetry or io.opentelemetry.api.trace.Tracer but always get unsatisfied dependency exception.

Is it actually possible to add spans by code in an auto-instrumented application?

My depdendencies:
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-opentelemetry</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-api</artifactId>
      <version>1.13.0</version>
  </dependency>
```

Also tried addinally the deps from the docu (https://aws-otel.github.io/docs/getting-started/java-sdk/trace-manual-instr) but unsatisfied dependency exception persists.

So still cannot create a tracer actually.

**Comment by Aneurysm9** [comment]
Can you please provide more detail and, ideally, a minimal reproduction case?  It's not clear to me right now where the issue lies.  Thanks.
