### ISSUE TITLE
Java sample app and documentation updated for metrics GA

### ISSUE THREAD

**Issue by mhausenblas** [aws-observability/aws-otel-java-instrumentation#186]
When [Java SDK](https://github.com/open-telemetry/opentelemetry-java) and [instrumentation](https://github.com/open-telemetry/opentelemetry-java-instrumentation) goes GA for metrics make sure that:

1. The sample and tests are up to date.
2. The relevant parts of the ADOT docs are updated.
3. The auto-instrumentation agent (JAR file) is updated.

Note: this SDK is a dependency of our ADOT [Lambda](https://aws-otel.github.io/docs/getting-started/lambda) offering.

**Comment by rapphil** [comment]
https://github.com/aws-otel/aws-otel.github.io/pull/371

**Comment by rapphil** [comment]
https://github.com/aws-observability/aws-otel-community/pull/99
