### ISSUE TITLE
Release v1.16.0

### ISSUE THREAD

**Issue by syr** [aws-observability/aws-otel-java-instrumentation#192]
Are there already plans when AWS Otel Agent will be available based on new opentelemetry release 1.16.0 which was released 8 days ago (https://github.com/open-telemetry/opentelemetry-java/releases)?

Version 1.16.0 contains an important bugfix, which I can not retest atm, because the agent from opentelemetry, does not generate valid trace IDs for XRay

**Comment by gautam-nutalapati** [comment]
It also contains dropwizard-metrics module which we need.

**Comment by bryan-aguilar** [comment]
[`v1.16.0`](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/tag/v1.16.0) released
