### ISSUE TITLE
Version 1.19.0 not available in releases

### ISSUE THREAD

**Issue by Sufyan-wawa** [aws-observability/aws-otel-java-instrumentation#243]
**Version 1.19.0**

Version `1.19.0` not available in releases https://github.com/aws-observability/aws-otel-java-instrumentation/releases

Recently below changes were done in this PR https://github.com/aws-observability/aws-otel-java-instrumentation/commit/3e31ad468623e44d49946f03a4a779d832c3ee69 to fix some CVES's.

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
1.19.0 should be available in maven central.
https://search.maven.org/artifact/software.amazon.opentelemetry/aws-opentelemetry-agent

**What did you see instead?**
A clear and concise description of what you saw instead.

**Additional context**
Not able to download the jar for 1.19.0.

**Comment by rapphil** [comment]
Hi, we are working on releasing this new version.

**Comment by rapphil** [comment]
ETA is today by the end of the day.

**Comment by rapphil** [comment]
We got delayed fixing issues in the release process and the release got postponed by a day.

**Comment by gdohmeier-wawa** [comment]
will there be a v1.19 release today? eta?

**Comment by rapphil** [comment]
v1.19.0 was released https://github.com/aws-observability/aws-otel-java-instrumentation/releases/tag/v1.19.0
