### ISSUE TITLE
Example of how to propagate traces from SQS

### ISSUE THREAD

**Issue by rjacobs91** [aws-observability/aws-otel-java-instrumentation#244]
**Is your feature request related to a problem? Please describe.**
From these [AWS docs](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-sqs.html) we can see that it is possible to recover the trace context from SQS messages and propagate for future calls to downstream services/queues using X-Ray. 

The existing implementation for AWS OTEL agent stops traces at the end of the [ReceiveMessage method call](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/aws-sdk/aws-sdk-1.11/library/src/main/java/io/opentelemetry/instrumentation/awssdk/v1_11/TracingRequestHandler.java#L77). It is the same implementation for v2 as well, so it would appear we need to manually instrument in our code base.

**Describe the solution you'd like**
We need an example of how to manually propagate the trace context using OpenTelemetry libraries similar to X-Ray in [here](https://docs.aws.amazon.com/xray/latest/devguide/xray-services-sqs.html). I assume we can manually instrument in additional to using the agent?

**Comment by willarmiros** [comment]
We should document this in the short term, and in the long term build an instrumentation class that automatically extracts the SQS trace context into a span per message received

**Comment by rjacobs91** [comment]
Any rough ETA for documentation?

**Comment by willarmiros** [comment]
Unfortunately we cannot provide ETAs, but we will link it here as soon as available!

**Comment by guadalupe-duolingo** [comment]
Is there any update on this?

**Comment by wangzlei** [comment]
Seems there is an experimental feature ["otel.instrumentation.aws-sdk.experimental-use-propagator-for-messaging"](https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/aws-sdk#settings-for-the-aws-sdk-instrumentation)
