### ISSUE TITLE
Invalid X-Ray trace Id with direct gRPC call (ALB + EKS)

### ISSUE THREAD

**Issue by BT-22** [aws-observability/aws-otel-java-instrumentation#251]
**Describe the bug**

- Using `grpcurl` to send a gRPC call directly to a service in our `ALB + EKS` setup, we can verify all [examples](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html).
- Our Istio ingress gateway log also indicates the forwarding of header `X-Amzn-Trace-Id`.
- The service uses `aws-opentelemetry-agent.jar` for auto-instrumentation.
- While the gRPC call executes successfully, we don't have an X-Ray trace.

**Steps to reproduce**
1. When a gRPC call arrives, the service sees an error message from the aws otel agent:
> [otel.javaagent 2022-10-27 17:04:52:358 +0000] [grpc-default-executor-27] ERROR io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug - Unexpected non-root current context found when extracting remote context!
2. An interceptor in the service sees the header `X-Amzn-Trace-Id` is indeed forwarded to the gRPC server.
3. However, it seems like it's not picked up, and a new trace identifier is generated - which is **not** valid for X-Ray:
> 2022-10-27T17:04:52,359 | [grpc-default-executor-27] | [c.i.a.i.a.i.Interceptor] | INFO | idsvc | traceId: 1-b3667db0-4d3751b9b59a29fe07837643 spanId: f5ce5ccf5e1f9f01 | tenantId: | ******** x-amzn-trace-id from client Self=1-635aba34-538789d31f1b504d3af48d29;Root=1-6350b8d5-93164eabb1697bcd9d3e7ca8

In the log message, the `x-amzn-trace-id` has both `Root` and `Self` in the right format; but the `traceId` has the invalid timestamp `b3667db0`, hence we do not have a trace.

We read `traceId` from `AWS-XRAY-TRACE-ID`.

**What did you expect to see?**
A valid X-Ray trace Id specified in the request, or generated by the ALB, should be propagated by the aws otel agent.

**What did you see instead?**
The direct gRPC call logs an invalid X-Ray trace Id, and there is no trace for the call.

**Additional context**
If the gRPC call is not the very first call, but invoked by another service, in our `API Gateway + NLB + EKS` setup, then the full end-to-end trace does work, and the gRPC call has its segments.

It's the same EKS and the same service pods that are behind both the `API Gateway + NLB + EKS` and the `ALB + EKS`.
So, we're puzzled by the situation.
- Is it something we're missing in configuring `ALB + EKS`?
- Or is it something we're missing in configuring the aws otel agent?
- Or is there something special about gRPC call being the first service?

FWIW: In a simplified setup, I run both the service with aws otel agent, and run aws otel collector locally on a PC, without ALB or Istio.
I send the header `X-Amzn-Trace-Id` in the gRPC request, and it seems like it's also not picked up, and a new trace Id is generated.
Except in this local setup, the newly generated trace Id is valid for X-Ray (hence I do see a trace).

**Comment by BT-22** [comment]
Just want to add some observations in my "local testing" without ALB:

I have an open API running in a docker container.
I have another docker container running gRPC API.
Both containers are using aws otel java agent with auto-instrumentation.

If I use curl to hit the open API first, which in turn makes a gRPC call, it appears the gRPC call gets the trace Id from the caller and uses it as trace Id.
If I use grpcurl to hit the gRPC API directly, even if I send the trace header, a new trace id is generated.

When these containers run with ALB + EKS, I see the direct gRPC call also generates a new trace id, not taking the ALB trace id header.
But for some reason, the generated new trace id is not valid - the timestamp part appears to be just random.

----
I will try to understand more; and if there is any suggestion how I may be able to debug further, please let me know.

**Comment by willarmiros** [comment]
Hi @BT-22,
Thanks for posting this issue. The problem with ALB is that it generates an `X-Amzn-Trace-Id` header with only the `Root` field for a trace ID, and doesn't include a parent Span ID. The OTel SDK doesn't accept this as a valid context, rejects it, and generates a new trace ID. This issue is documented here: https://github.com/aws-observability/aws-otel-collector/issues/738. APIGateway for instance *does* include the Parent ID, which is why that case works.

For your EKS service though, it sounds like there may be an issue with the ID generator if it is not producing X-Ray compliant trace IDs in the new context with the aws-otel-java-agent. 

@BT-22 can you provide the version of the aws-otel-java-agent you're using and @rapphil can you take a look to make sure there is nothing wrong with the ID generator in that version of the agent?

**Comment by BT-22** [comment]
Thanks for the reply, @willarmiros - very helpful.

Based on your explanation, I tried to send in the requests something like `X-Amzn-Trace-Id: Parent=1234567890abcdef` or `X-Amzn-Trace-Id: Root=1-6366d5a6-58e37bfb695cab015e1a0000;Parent=1234567890abcdef` and both generated traces in our ALB + EKS setup.

Our aws-otel-java-agent should be `1.13.1-aws` according to debug log:

> [otel.javaagent 2022-11-05 02:40:05:346 +0000] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: 1.13.1-aws
> [otel.javaagent 2022-11-05 02:40:05:347 +0000] [main] DEBUG io.opentelemetry.javaagent.tooling.VersionLogger - Running on Java 17.0.3. JVM OpenJDK 64-Bit Server VM - Eclipse Adoptium - 17.0.3+7
> [otel.javaagent 2022-11-05 02:40:05:347 +0000] [main] DEBUG io.opentelemetry.javaagent.tooling.AgentInstaller - io.opentelemetry.javaagent.tooling.AgentInstaller loaded on io.opentelemetry.javaagent.bootstrap.AgentClassLoader@378fd1ac

**Comment by willarmiros** [comment]
Got it, glad we could provide a workaround! As for the trace ID generation issue, v1.13.1 is quite a few months old, the latest is v1.19.2. Please let us know if that version is still impacting your trace ID generation (downloadable here: https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/v1.19.2/aws-opentelemetry-agent.jar)

**Comment by BT-22** [comment]
Thanks! Will test and update here...

**Comment by BT-22** [comment]
I've tested v1.19.2 and unfortunately the behavior is identical to v1.13.1

When I send a gRPC call to ALB and it lands on the service pod, a new trace ID is generated but the timestamp part is obviously wrong.

The 2 workarounds of specifying `Parent` continue to work.

**Comment by lorelei-rupp-imprivata** [comment]
@willarmiros any other suggestions here, the latest also doesn't seem to work for us either

**Comment by willarmiros** [comment]
@rapphil would you mind assisting with the investigation here? There are 2 possibilities it seems. Either:
1. The AWS Java agent is not using the X-Ray ID generator at all, which would be a major issue that needs to be resolved, OR
2. There is some edge case where if the X-Ray propagator receives an invalid trace context (e.g. with only the trace ID and no parent ID), the OTel SDK does not respect the X-Ray ID generator and uses the default ID generator.

Relevant file where the log message occurred: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation-api/src/main/java/io/opentelemetry/instrumentation/api/internal/ContextPropagationDebug.java#L78

@BT-22 could you provide any additional logging that occurred around the line you already provided? 

> Unexpected non-root current context found when extracting remote context!

It seems we may do some additional debug logging around there.

**Comment by rapphil** [comment]
Hi @willarmiros . Possibility 1 can be ruled out as we have integration tests that validate that every agent release is able write to X-Ray. This would affect everyone using the agent.

I will have to dig more to investigate possibility 2.

**Comment by BT-22** [comment]
Happy New Year @willarmiros and @rapphil 
I'll capture the full log and attach it in my next comment

**Comment by BT-22** [comment]
Hello, I ran a single pod for the service, and after it's running for a while, I ran a manual gRPC request that passed ALB then hit the service.
In the gRPC request I did not specify the X-Amzn-Trace-Id header, and ALB generated one with a valid X-Ray trace ID as Root, but without parent span ID. 
Then, in our service, that X-Ray trace ID was not used, instead, a new trace ID that is not in X-Ray format was generated.

[log.zip](https://github.com/aws-observability/aws-otel-java-instrumentation/files/10357069/log.zip)

It is in the end portion of the log, where you can see
```
2023-01-06T02:46:07,982 | [grpc-default-executor-0] | [c.i.a.i.a.a.u.v.IdentityUserServiceV2] | WARN | idsvc | traceId: 1-bab416ea-b95e614bc8d026a7fb790712 spanId: 5f71390f0e15250b | tenantId:

L63RLPDBXGA36 | ApiError: code=not-found, message=No user found¶
```
The invalid ID is 1-bab416ea-b95e614bc8d026a7fb790712
(and the gRPC response with `ApiError: code=not-found, message=No user found` is intentional and not of interest)

A bit earlier in the log, you can see 
```
[otel.javaagent 2023-01-06 02:46:07:286 +0000] [grpc-default-executor-0] ERROR io.opentelemetry.javaagent.shaded.instrumentation.api.internal.ContextPropagationDebug - Unexpected non-root current context found when extracting remote context!
```
among other debug messages.

A bit later there are a few `Invalid TraceId in B3 header: null'. Returning INVALID span context.` but I'm not sure if they're related.

**Comment by BT-22** [comment]
Hello, I'd like to describe a new finding, now that I'm testing again, and based on your comments and my further inspecting/testing in our environment...

in our deployment manifest, we have `OTEL_PROPAGATORS='b3,xray'`
It does not seem to cause any issue when we're using API Gateway
but it probably is triggering the issue we're discussing when it comes to ALB+gRPC

here's what I found:

If I change the setting to  `OTEL_PROPAGATORS='xray'`
then when my gRPC request without the X-Amzn-Trace-Id header passes ALB then hits the gRPC service, I get valid X-Ray trace ID and I see trace indeed. The ALB generated Root trace ID must be working in this case.
So it would seem that in this case, having both b3 and xray is causing the issue. I tested, `b3,xray` or `xray,b3` made no difference. Only after I have deleted b3 then I will get traces.

**Comment by wangzlei** [comment]
I cannot explain this behavior of log `Invalid TraceId in B3 header: null'. Returning INVALID span context.`

ADOT javaagent hardcode propagators as [`xray,tracecontext,b3,b3multi`](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/f1dc5969ba5d47694a07500b90ffd83f0829d545/awsagentprovider/src/main/java/software/amazon/opentelemetry/javaagent/providers/AwsAgentProperties.java#L26). Users can override propagators by environment variable `OTEL_PROPAGATORS`.
If a request to ALB contains no X-Ray header and no B3 multi header, ALB will send an incomplete X-Ray trace header which is incompatible with ADOT javaagnet, this is a known issue today we don't have solution yet. The long term fix might be either change ALB behavior or customize ADOT javaagent to be able to handle imcomplete trace header(missing parent, or missing sample flag etc) 

But if there is no invalid B3 multi header `b3` in request, user should not see error log `Invalid TraceId in B3 header: null'. Returning INVALID span context.`

**Comment by bryan-aguilar** [comment]
Not stale
