### ISSUE TITLE
Span not created on SqsListener

### ISSUE THREAD

**Issue by SodaDev** [aws-observability/aws-otel-java-instrumentation#263]
**Describe the bug**
@SqsListener is not creating Span with Spring Boot using aws-otel agent

**What did you expect to see?**
Created Span

**What did you see instead?**
Created span like this one
PropagatedSpan{ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}}

**Additional context**
spring-cloud-aws-messaging-2.4.2.jar
Spring Boot version 2.7.4

**Comment by vsakaram** [comment]
related to https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/4788
