### ISSUE TITLE
Release request: upstream 1.20.0

### ISSUE THREAD

**Issue by dboreham** [aws-observability/aws-otel-java-instrumentation#272]
Hello, I'm not sure how much work it is to rebase this project on a new upstream version, but I figured worth asking if it would be possible to have a release based on upstream 1.20.0 (or later) published? I made a small performance fix (small fix, big performance difference for my app) that made it into 1.20.0 but our app uses the AWS agent. Hence the request. Hope that made sense and thanks!

**Comment by vasireddy99** [comment]
Hi @dboreham, Thank you so much for the request. We will update the correspondence here with any developments about the 1.20.0 release.

**Comment by rapphil** [comment]
Hi @dboreham , the ADOT Java 1.20.0 was just released. Please check it out in https://github.com/aws-observability/aws-otel-java-instrumentation/releases/tag/v1.20.0

Cheers!

**Comment by dboreham** [comment]
Thank you!
