### ISSUE TITLE
Lack of a docker image

### ISSUE THREAD

**Issue by RyanW8** [aws-observability/aws-otel-java-instrumentation#306]
**Is your feature request related to a problem? Please describe.**
We have the OpenTelemetry operator deployed to k8s. Part of this is the ability to auto instrument Java applications by injecting a sidecar containing the compiled agent. As we're using X-Ray we need to use this SDK as it defaults to using the X-Ray ID generator & propagator; however to use this SDK with the OTEL Auto instrumentation we had to build our own docker image.

```
FROM alpine:latest
ARG AWS_OTEL_JAVA_INSTRUMENTATION_VERSION=v1.20.0
ADD https://github.com/aws-observability/aws-otel-java-instrumentation/releases/download/$AWS_OTEL_JAVA_INSTRUMENTATION_VERSION/aws-opentelemetry-agent.jar /javaagent.jar
```

**Describe the solution you'd like**
It would be nice if AWS published a docker image for us and have it maintained as part of this repo rather than letting us do it. The docker file is very trivial so should be a straight forward to implement. **NOTE** the operator expects the Java agent to be available at `/javaagent.jar`

**Comment by rapphil** [comment]
Hi @RyanW8 .
We are evaluating publishing a docker image containing the ADOT Java Agent. We don't have  a precise ETA to share at this time, but this should be available soon.

**Comment by rapphil** [comment]
Hi @RyanW8 we just released a Docker image that is compatible with the image used by the Operator: https://gallery.ecr.aws/aws-observability/adot-autoinstrumentation-java

Please let me know if you have any questions.

**Comment by rapphil** [comment]
Closing as we will start providing this image with every release moving forward.
