### ISSUE TITLE
OTEL trace id mismatches with XRay trace id

### ISSUE THREAD

**Issue by fpaparoni** [aws-observability/aws-otel-java-instrumentation#318]
I'm using ADOT and automatic instrumentation for my service. Using the following information in my Spring Boot logback configuration

`%mdc{trace_id}, %mdc{span_id}`

I can see as usuale the OTEL trace id and span id. Now I'm also using the XRay exporter and from I can understand there a "rework" of the OTEL trace id to be suitable for XRay. Related to the same trace I have the following mismatch

```
OTEL Trace id : 63d2a17a67b226c5725ef0886f25c040 
XRay Trace id: 1-63d2a17a-67b226c5725ef0886f25c040
```

I can understand the motivation to create a specific id compliant with XRay format, but is there a way to log the XRay trace id in application log? Because otherwise if I log something using OTEL trace is, I won't be able to find it on XRay and so XRay cannot be useful in that way

**Comment by rapphil** [comment]
Hi @fpaparoni ,

The trace id of xray is compatible with the trace id of OpenTelemetry in its binary representation. For textual representation, the OpenTelemetry Trace Id has to be converted into the X-Ray trace id format.

If you are using the ADOT Java Agent, you can use the MDC key `AWS-XRAY-TRACE-ID`. Here is an example: https://github.com/aws-observability/aws-otel-community/blob/master/sample-apps/java-sample-app/auto/src/main/resources/log4j2.xml#L6

This sample application is producing logs with traces id in the X-Ray format: https://github.com/aws-observability/aws-otel-community/tree/master/sample-apps/java-sample-app

**Comment by fpaparoni** [comment]
Hi @rapphil ,

thank you very much. I tried the MDC key and it works. If I'm using the autoinstrumentation it's ok, but if I want to manually instrument my application I can obtain the standard OTEL information using the API. The following is the information I can obtain from Tracer/Span/SpanContext API

`ImmutableSpanContext{traceId=63d7cb1c9a741987408b63926c0482b5, spanId=4f7155b3cb6e7169, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}`

Is there a programmatic way to retrieve also the X-Ray trace id?

**Comment by fpaparoni** [comment]
Or if there isn't a way to retrieve it in a programmatic way (because there isn't the an API ad-hoc with this field) is there a way to recreate it?

I see this OTEL trace id

63d938a82eced0a5153061e66a4133bc

and corresponding X-Ray id in AWS

1-63d938a8-2eced0a5153061e66a4133bc

it seems an easy mapping (1-first 8 chars-last 24 chars) but probably it's more complex ;)

**Comment by bryan-aguilar** [comment]
> it seems an easy mapping (1-first 8 chars-last 24 chars) but probably it's more complex ;)

It is indeed that easy :)

For ref [this](https://docs.aws.amazon.com/xray/latest/devguide/xray-api-sendingdata.html#xray-api-traceids) is a good primer on the traceid format for x-ray if you have not seen it.

**Comment by fpaparoni** [comment]
wow great :)

thank you very for the link to the docs
