### ISSUE TITLE
Trace Id (x-amzn-trace-id) missing in Spring Boot HTTP response

### ISSUE THREAD

**Issue by otbe** [aws-observability/aws-otel-java-instrumentation#37]
Hello 

**Describe the bug**
We used the old Xray SDK before we switched to otel-collector/javaagent this month. Right now we're missing the "x-amzn-trace-id" header in our API responses.

**What did you expect to see?**
x-amzn-trace-id should be present in http responses.

**Additional context**
v.0.6.0 sidecar and v0.12.1-aws.1 agent

Is this expected/work in progress or do I miss something?

Thanks

**Comment by anuraaga** [comment]
Hi @otbe - OpenTelemetry currently does not support returning trace headers in responses. The design is based on w3c, which is currently speccing out how to handle them, the support would probably come to OpenTelemetry some time after that.

Just curious, how do you use the response header?

**Comment by otbe** [comment]
Thanks for the answer @anuraaga . We currently expose the traceId (header value) to our customers on some error pages. Its quite useful for debugging stuff.

Is there any workaround (filters) known for our SB setup?

**Comment by anuraaga** [comment]
@otbe We don't have anything automatic at the moment, but you should be able to access the current span information in the context with `Context.current()`. While we only use the propagator to inject into a downstream request currently, I guess it should work for a response in a filter too.

https://github.com/open-telemetry/opentelemetry-java/tree/main/extensions/trace-propagators

`AwsXrayPropagator.inject(Context.current(), response, HttpServletResponse::setHeader)`

**Comment by otbe** [comment]
Thanks for the answer again. I tried something like this

```
@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class XrayHeaderFilter implements Filter {
  @Override
  public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
      throws IOException, ServletException {
    val res = (HttpServletResponse) response;

    AwsXrayPropagator.getInstance().inject(Context.current(), res, HttpServletResponse::setHeader);

    chain.doFilter(request, response);
  }
}
```

and in my pom.xml
```
<dependency>
	<groupId>io.opentelemetry</groupId>
	<artifactId>opentelemetry-extension-trace-propagators</artifactId>
</dependency>
```

The filter kicks in but sadly the header is not added to the response. Do I need to setup opentelemetry within our SB app to get this to work? For reference we currently use the java agent, so there is no dedicated setup in our app.

**Comment by anuraaga** [comment]
@otbe Thanks for trying this, the code looks like what we'd expect to work so I'm going to have to experiment on my end to see what could be happening. Hopefully we figure it out, sorry for the trouble.

**Comment by otbe** [comment]
FYI: just verified that in general setting a header works this way. I added `res.setHeader("foo", "bar");` right before the AwsXrayPropagator and it showed up in the response.

**Comment by anuraaga** [comment]
Hi @otbe sorry for the delay on this, I could finally try to populate headers. I created a filter basically the same as your snippet here

https://github.com/aws-observability/aws-otel-playground/blob/main/frontend/src/main/java/com/softwareaws/xray/examples/Application.java#L122

and can confirm the response from that app contains the `X-Amzn-Trace-Id` header. It's a very standard spring boot application, and I just use the `-javaagent:` parameter to add the agent. Can you think of any difference between your app and that link's code?

**Comment by otbe** [comment]
Thanks @anuraaga 

Unfortunately not. I gave it another try and also updated the opentelemetry bom to `0.15.0` which should be the latest version. The `AwsXrayPropagator` class looks now more like the one you posted.
Still no trace id header in the response.
Maybe something...in your gradle file you have a lot of aws xray dependencies -> https://github.com/aws-observability/aws-otel-playground/blob/main/frontend/build.gradle.kts#L19 which is not present in our setup.

Our little app runs on top of ECS/Fargate and with ALB in front of it.

**Comment by anuraaga** [comment]
@otbe I believe this may be a mismatch between the API version and the agent version - until 1.0, there is a strict requirement for those two to match for some functionality to work, such as reading the current Span in business logic. The playground currently targets snapshots which is why it is using 0.15.0.

I'll be releasing an agent based on 0.15.0 shortly and it might be best to wait for that just to make sure there aren't any other already-fixed bugs that are affecting us here.

**Comment by otbe** [comment]
Sounds good @anuraaga 👍
Ill keep an. eye on.https://github.com/aws-observability/aws-otel-java-instrumentation/releases :)

**Comment by anuraaga** [comment]
@otbe So sorry for the long delay, the new version has been released. Let's see if it helps

**Comment by otbe** [comment]
Big thank you @anuraaga 

It finally works 👍 
It was really about the mismatch of the versions, I should've read more carefully the release page. I think we can close this issue for the time being. Maybe we can document the way (filter + dependency) somewhere, so people dont have to search for github issues :)
