### ISSUE TITLE
Trace id added to MDC is misleading

### ISSUE THREAD

**Issue by otbe** [aws-observability/aws-otel-java-instrumentation#38]
Hello,

**Describe the bug**
We use the java agent with one of our spring boot apps. The agent adds a traceId like `60108d573a343aec0c7a35f4ede1e064` to our log output but it should have been something like `1-60108d57-3a343aec0c7a35f4ede1e064`.

**What did you expect to see?**
Maybe the proper traceId copy&paste'ble to Xray? Im not quite sure what is the expected behavior here.

**Additional context**
v.0.6.0 sidecar and v0.12.1-aws.1 agent

Is this expected/work in progress or do I miss something?

Thanks

**Comment by anuraaga** [comment]
Thanks @otbe for this report, it hadn't come to mind yet. The trace ID is formatted in OpenTelemetry format there, but indeed it means the ID isn't copy-pastable into a query on the x-ray console which is problematic. I don't think there is a quick fix here, but we will try to get something working to make the query correlation easier.

**Comment by otbe** [comment]
Lemme me know if I can help. We want to move fully into the xray+otel business.

**Comment by anuraaga** [comment]
@otbe We're currently thinking of allowing the console to be queried using the unformatted ID e.g., `60108d573a343aec0c7a35f4ede1e064`. Would this solve your issue? It'll take some time I think to make this happen unfortunately.

In the meantime, the only workaround that comes to mind is a custom logback (are you using logback?) appender which reformats the ID field when it's present. Haven't played with the idea yet to know if it's even feasible though.

**Comment by otbe** [comment]
Hi @anuraaga that would be really nice.
And yes we're using logback/logstash and added a step to the pipeline to reformat the ID according to https://github.com/open-telemetry/opentelemetry-java/blob/main/extensions/trace-propagators/src/main/java/io/opentelemetry/extension/trace/propagation/AwsXrayPropagator.java#L94

**Comment by anuraaga** [comment]
> and added a step to the pipeline to reformat

So right now you are ok? If so, phew, thanks for doing that. Hope we can make this more seamless soon.

**Comment by otbe** [comment]
Yes we're ok with our little workaround for the time being :)

**Comment by anuraaga** [comment]
@otbe Thanks for the patience - I've sent #49 with the ability to inject the x-ray formatted ID just like xray SDK. Hopefully this will help with your use case :)
