### ISSUE TITLE
Update actions to not use Node.js 12

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-java-instrumentation#398]
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/

https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/codeql-analysis.yml
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/main-build.yml
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/nightly-upstream-snapshot-build.yml
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/pr-build.yml
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/release-build.yml
https://github.com/aws-observability/aws-otel-java-instrumentation/actions/workflows/docker-build-smoke-tests-fake-backend.yml

**Comment by rapphil** [comment]
All workflows were migrated to Node 16
