### ISSUE TITLE
xray tracing stops after some hours

### ISSUE THREAD

**Issue by DavidSchwarz2** [aws-observability/aws-otel-java-instrumentation#446]
**Setup:** 
AWS ECS, Spring boot 3.1 app and the aws-opentelemetry-agent (v1.26.0 / v1.27.0)
The agent is configured like this (in the Dockerfile):
ENV OTEL_TRACES_SAMPLER "always_on"
ENV OTEL_TRACES_EXPORTER "otlp"
ENV OTEL_PROPAGATORS "tracecontext,baggage,xray"
ENV OTEL_IMR_EXPORT_INTERVALL "5000"
ENV OTEL_EXPORTER_OTLP_ENDPOINT "http://localhost:4317/"

The collector runs as sidecar in ecs and uses the configuration: /etc/ecs/ecs-xray.yaml
OpenTelemetry Collector (ADOT Collector)
It is from the tutorial: https://catalog.us-east-1.prod.workshops.aws/workshops/31676d37-bbe9-4992-9cd1-ceae13c5116c/en-US/aws-managed-oss/adot/javawalkthrough

**Problem:**
When starting the ecs the xray tracing works fine. After some hours it stops tracing to xray.
The collector debug logs gives many errors like:
`ErrorCode: "InvalidSegment",
2023-06-20T14:52:43.373Z	Id: "69d51772dffdb29c",
2023-06-20T14:52:43.373Z	Message: "Trace Size Exceeded. Reduce the number of segments per trace and the size of your segment documents."`

**Assumptions:**
It seems like the trace ids are reused too often and the traces become too big.
(I did not add custom spans or something, but only using the auto-instrumentation.)

Is there a way configure the number of segment or the size of the segment documents while auto-instrumenting?
Or do I have to setup manual tracing?

**Comment by DavidSchwarz2** [comment]
Hi rapphil,

**Comment by DavidSchwarz2** [comment]
Hi rapphil,
the traces prior to the error are looking ok.
Could it be that there are problems with parallel processing? We are using kotlin coroutines to do things in parallel.

Here are the complete logs of one example call:
```
info TracesExporter {"kind": "exporter", "data_type": "traces", "name": "logging", "resource spans": 1, "spans": 19}
2023-07-03T09:40:25.135Z debug awsxrayexporter@v0.76.3/awsxray.go:68 TracesExporter {"kind": "exporter", "data_type": "traces", "name": "awsxray", "type": "awsxray", "name": "awsxray", "#spans": 7}
2023-07-03T09:40:25.135Z debug awsxrayexporter@v0.76.3/awsxray.go:80 request: {
TraceSegmentDocuments: [
"{\"name\":\"<snip...s3 call>\"type\":\"subsegment\"}\n",
"{\"name\":\"<snip...s3 call>",
"{\"name\":\"<snip...database call>",
"{\"name\":\"<snip...>",
"{\"name\":\"HealthController.health\",\"id\":\"d2336dcff1eec3d9\",\"start_time\":1688377221.398077,\"service\":{\"version\":\"7a083a57c8ec9cecb2bcc7b6e3d64ca29332a1e44ffc331e99043c9f649435a6\"},\"origin\":\"AWS::ECS::Fargate\",\"trace_id\":\"1-64a28428-03698151c619e1014355530a\",\"end_time\":1688377221.4458563,\"fault\":false,\"error\":false,\"throttle\":false,\"aws\":{\"cloudwatch_logs\":[{\"log_group\":\"<snip...>\"parent_id\":\"e7f85d8dc4ed1cf1\",\"type\":\"subsegment\"}\n",
"{\"name\":\"<snip...>"type\":\"subsegment\"}\n",
"{\"name\":\"<snip...>\"type\":\"subsegment\"}\n"
]
} {"kind": "exporter", "data_type": "traces", "name": "awsxray"}
2023-07-03T09:40:25.155Z debug awsxrayexporter@v0.76.3/awsxray.go:90 response: {
UnprocessedTraceSegments: [
{
ErrorCode: "InvalidSegment",
Id: "09eb84f2fd77cb63",
Message: "Trace Size Exceeded. Reduce the number of segments per trace and the size of your segment documents."
},
{
ErrorCode: "InvalidSegment",
Id: "e4032e122cd6575b",
Message: "Trace Size Exceeded. Reduce the number of segments
```

**Comment by atshaw43** [comment]
This error can also occur if you are rate limited. I see you have always on sampling. With a high enough transaction per second you could go past your limit. Are you able to lower the sampling rate?

ENV OTEL_TRACES_SAMPLER "always_on"

**Comment by atshaw43** [comment]
This can occur by you having a large number of traces and you get rate limited.
Can you try a percentage based sampling rate instead of always on?

**Comment by DavidSchwarz2** [comment]
Hi,
I tried it with OTEL_TRACES_SAMPLER "traceidratio" and OTEL_TRACES_SAMPLER_ARG “0.25”. 
This had no effect. 
I tried the plain aws sdk with the aws x-ray daemon and it seems that there are problems with multithreading. 
I removed our multithreading code for the test and it seems to work.

**Comment by atshaw43** [comment]
This looks like a bug around instrumentation then.
Can you make a minimal code sample that reproduces the issue?
