### ISSUE TITLE
Very long "cold run" with AWS OT Java Agent

### ISSUE THREAD

**Issue by mat-rumian** [aws-observability/aws-otel-java-instrumentation#48]
**Describe the bug**
It takes very long time to run the AWS Lambda Java function instrumented by AWS OTEL Java Agent. In case of very simple function which makes only HTTP GET requests it takes around 40-45 seconds to run the code. (cold run) and it is causing some Lambda HTTP response timeouts - later it's smooth.

**Steps to reproduce**
[aws-opentelemetry-agent.jar](https://github.com/aws-observability/aws-otel-java-instrumentation/releases/latest/download/aws-opentelemetry-agent.jar) set as `-javaagent`
*lambda function code*
```
package example;

import static java.util.stream.Collectors.toMap;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyRequestEvent;
import com.amazonaws.services.lambda.runtime.events.APIGatewayProxyResponseEvent;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.impl.client.HttpClients;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Map;
import java.util.concurrent.TimeUnit;

public class HelloLambdaHandler implements RequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {

    @Override
    public APIGatewayProxyResponseEvent handleRequest(APIGatewayProxyRequestEvent request, Context context) {
        APIGatewayProxyResponseEvent response = new APIGatewayProxyResponseEvent();
        response.setStatusCode(200);
        try {
            response.setHeaders(request.getHeaders().entrySet()
                                       .stream()
                                       .map(e -> Map.entry("received-" + e.getKey(), e.getValue()))
                                       .collect(toMap(Map.Entry::getKey, Map.Entry::getValue)));
        } catch (Exception e) {}

        HttpClient httpclient = HttpClients.createDefault();
        for(int i = 0; i < 3; i++) {
            try {
                HttpResponse httpResponse = httpclient.execute(new HttpGet("http://httpbin.org/"));
                httpResponse.getEntity().getContent().readAllBytes();
            } catch (Exception e) {
            }
        }

        Throwable t = new Throwable();
        StringWriter writer = new StringWriter();
        t.printStackTrace(new PrintWriter(writer));
        response.setBody("I'm lambda!\n" + writer.toString());

        return response;
    }
}
```

**What did you expect to see?**
I expect to start the Lambda much faster. In case of [OpenTelemetry Java Agent](https://github.com/open-telemetry/opentelemetry-java-instrumentation) it is 9 seconds

**What did you see instead?**
![image](https://user-images.githubusercontent.com/58699800/111225861-99891b00-85e0-11eb-87a1-1cfcaaec2d78.png)

**Additional context**

**Comment by anuraaga** [comment]
Hi @mat-rumian - the aws java agent is almost the same binary as the OpenTelemetry upstream one so it's really surprising if they have different performance. I tried with the upstream one a while ago and found it to have similar 40-50s overhead with normal functions, and around 10s with provisioned concurrency. Can you confirm the function configuration was the same when trying the two agents? I'll try to confirm on my end too.

**Comment by anuraaga** [comment]
@mat-rumian - I tried the upstream agent and had similar performance profiles to the AWS distro. No provisioning, ~60s, with provisioning, ~10s. This is unfortunately just the nature of doing significant bytecode manipulation at runtime I'm afraid. 

One trick to try could be to disable instrumentation by default and only enable the ones you need, using `-Dotel.instrumentation.common.default-enabled=false`. For example, this enables only annotatinon processing

https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/suppressing-instrumentation.md#enable-manual-instrumentation-only

**Comment by anuraaga** [comment]
@drissamri I have heard that Quarkus team is working on being able to run a java agent during compile time which would probably make the Java agent practical on lambda, even without provisioned concurrency! I'm not sure of a roadmap or any issues to follow related to it, my understanding is the effort just started.
