### ISSUE TITLE
Does the xray remote sampler respect parent sampling decision?

### ISSUE THREAD

**Issue by otbe** [aws-observability/aws-otel-java-instrumentation#516]
Hello,

this is neither a bug nor a feature request, sorry for misusing the issue tracker here but I was unable to find the answer.

Imagine we have a central service `C` which is used by service `A` and `B` (via grpc).  
`A`, `B` and `C` use the aws otel java agent and are configured to use the xray remote sampler. So, `OTEL_TRACES_SAMPLER` is set to `xray`. 

Wanted behaviour is now: whenever  `A` or `B` decide to sample a request, also `C` should do this. Before the remote sampler was introduced I used `parentbased_traceidratio` for my service `C` and it worked as expected. Now I have the feeling this does not work (or at least not reliable).

So my question is, if I configure service `C` to also use `xray` sampler does it respect the sampling decision of `A`/`B` or will it just look for the sampling rules in xray and decide on its own?

Thank you very much :)

**Comment by vastin** [comment]
If service `C` use `xray` sampler, it will respect the sampling decision of `A`/`B` with `parentbased` sampler. If sampling decision of  `parentbased` sampler is not sampled, it will use `OrElse` sampler to make remote sampling decision. The related code is [here](https://github.com/open-telemetry/opentelemetry-java-contrib/blob/main/aws-xray/src/main/java/io/opentelemetry/contrib/awsxray/AwsXrayRemoteSamplerBuilder.java#L98).
