### ISSUE TITLE
AWS Resource Attributes gathering

### ISSUE THREAD

**Issue by CeeBeeCee** [aws-observability/aws-otel-java-instrumentation#55]
Is it possible for the AWS javaagent to capture AWS specific resource attributes like region, availability zone, ECS ARN, Container memory and CPU limits etc as per the OTel Cloud Semantic Conventions? At the moment, we're using the OTel Javaagent and using AOP to inject these attributes as span attributes but these are truly resource attributes and should be captured as such.

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/cloud.md

**Comment by anuraaga** [comment]
Hi @CeeBeeCee - we currently collect a few attributes in this code

https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource

Just wondering are you using Fargate? I'm a bit surprised you're not seeing region / zone if they're EC2 instances

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/aws/src/main/java/io/opentelemetry/sdk/extension/aws/resource/Ec2Resource.java#L97

There are a lot more attributes we could collect in the SDK and are always happy for help if it's possible. For now we are prioritizing adding attributes in the collector so they apply to all SDK languages in one go.

https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/resourcedetectionprocessor/internal/aws

In particular there's a lot of ECS stuff in there. Are you using this collector processor by any chance?

**Comment by CeeBeeCee** [comment]
Hi Anurag,

I only tested the AWS java agent locally. Most of our applications run on
Fargate using the OTel Javaagent and I can test the AWS agent. I was not
able to find the AWS java agent on maven. repo https://mvnrepository.com/

Are you releasing the agent to Maven Repo yet? We're only allowed to deploy
apps that use artifacts from Maven. If you send me the maven coordinates, I
will test it and let you know.

Thanks
--Sib

**Comment by CeeBeeCee** [comment]
As for the approach of letting the collector collect resource attributes instead of the SDK, is there an assumption that folks would be running the collector as a sidecar? We run a central collector for all of the company on a fleet of EC2s which receive traces from Java/Python/Node SDKs running on ECS, EKS and Lambdas. If we were to enable the AWS resource detection processor on the collector instances, wouldn't the EC2 attributes get appended to all traces? Trying to understand how this would work.

**Comment by anuraaga** [comment]
Hi @CeeBeeCee - we publish the agent to Maven Central as well

https://mvnrepository.com/artifact/software.amazon.opentelemetry/aws-opentelemetry-agent

We have discussed adding the AWS resource extension to the upstream otel agent as well as it's not x-ray specific but have not made that change yet. In the meantime, the aws distro should work ok.

> is there an assumption that folks would be running the collector as a sidecar?

There indeed is - currently we recommend using sidecar, primarily to unlock the rich resource detection code there. Indeed in your setup where you run the collector as a service, it's not going to help. For this case, we understand the need for SDKs to extract as well, but have not been able to prioritize the development for these vs other features at the moment. PRs would be really appreciated though if you have the means :)
