### ISSUE TITLE
AWS OTEL agents in Docker images

### ISSUE THREAD

**Issue by AlexJov** [aws-observability/aws-otel-java-instrumentation#566]
**Is your feature request related to a problem? Please describe.**
When instrumenting applications running in containers e.g. Elastic Container Service (ECS), I'd like to have an option to add agent through init container and use agent binaries from mounted volume rather than adding agent to the monitored application image. 
Benefits would be 1) separated lifecycle of application and agent images so that different teams can manage them and updates in one are not tied to another, 2) no need to change (and re-publish) original application image when adding observability cross-teams, 3) achieving single-responsibility principle of containers. 
I would also argue that straight-forward way to include agent containers would decrease barrier to enter the observability space, as it would remove the need for each customer to create, harden and maintain agent images.

**Describe the solution you'd like**
Having otel instrumentation agents ready to use in Docker images, based on documentation already provided here: https://aws-otel.github.io/docs/getting-started/java-sdk/auto-instr#running-the-agent-in-docker

[+] References from the industry where delivering agent through init-container is mentioned as go-to approach:
- Elastic: https://www.elastic.co/guide/en/observability/current/monitor-kubernetes.html#_step_3_install_and_configure_apm_agents
- Datadog: https://docs.datadoghq.com/integrations/faq/integration-setup-ecs-fargate/?tab=rediswebui#update-the-task-definition (add container)
- AppDynamics: https://docs.appdynamics.com/appd/21.x/21.7/en/application-monitoring/install-app-server-agents/container-installation-options/instrument-kubernetes-applications-manually/use-init-containers-to-instrument-applications

ty

**Comment by mhausenblas** [comment]
Thanks for raising this issue and it's already possible but not well documented, let's discuss!
