### ISSUE TITLE
How do I log ServiceLens/X-Ray "User" with the OTEL agent?

### ISSUE THREAD

**Issue by stnor** [aws-observability/aws-otel-java-instrumentation#57]
**Is your feature request related to a problem? Please describe.**
II am trying to log the end-user username to X-ray with with the OTEL agent using the attribute "enduser.id".
I've verified that the code works locally, and that the attribute is added.

The metadata does not contain the attribute when in X-Ray:
```json
{
    "default": {
        "enduser.scope": "ROLE_USER USE_PREMIUM_TTS ROLE_STUDENT",
        "thread.name": "http-nio-8180-exec-21",
        "thread.id": ""
    }
}
```

Code:
```java
public abstract class AbstractSpringOpenTelemetryInterceptor {

    // see io.opentelemetry.semconv.trace.attributes.SemanticAttributes
    public static final String ENDUSER_ID = "enduser.id";
    public static final String ENDUSER_SCOPE = "enduser.scope";

    public static String INSTRUMENTATION_APP_PACKAGE = "se.nomp";
    private final Tracer tracer = GlobalOpenTelemetry.getTracer(INSTRUMENTATION_APP_PACKAGE);

    protected Object wrapWithSpan(ProceedingJoinPoint pjp) throws Throwable {
        Span span = tracer.spanBuilder(generateSubsegmentName(pjp)).startSpan();
        try (Scope scope = span.makeCurrent()) {
            var principalName = getPrincipalName();
            if (principalName != null) {
                span.setAttribute(ENDUSER_ID, principalName);
                var authorities = getAuthorities();
                if (authorities != null) {
                    span.setAttribute(ENDUSER_SCOPE, authorities);
                }
            }
            return conditionalProceed(pjp);
        } finally {
            span.end();
        }
    }

    protected String generateSubsegmentName(ProceedingJoinPoint pjp) {
        return pjp.getSignature().getDeclaringType().getSimpleName() + "." + pjp.getSignature().getName();
    }

    private static Object conditionalProceed(ProceedingJoinPoint pjp) throws Throwable {
        return pjp.getArgs().length == 0 ? pjp.proceed() : pjp.proceed(pjp.getArgs());
    }

    public static String getPrincipalName() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null) {
            return authentication.getName();
        }
        return null;
    }

    public static String getAuthorities() {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication != null) {
            var authorities = authentication.getAuthorities();
            if (authorities != null) {
                return authorities.stream().map(a -> a.getAuthority()).collect(Collectors.joining(" "));
            }
        }
        return null;
    }
}
```

**Describe the solution you'd like**
I'd like to know what I should be doing instead.

**Comment by anuraaga** [comment]
Hi @stnor - we actually map that into the X-Ray's native data model

https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/c3fb1c133fe7f227c7193fbbf72d22f22e18906e/exporter/awsxrayexporter/translator/segment.go#L333

Does user not show up in one of the tabs in the segment's details?

**Comment by stnor** [comment]
Not that I can see.

<img width="1585" alt="Screenshot 2021-05-18 at 08 37 35" src="https://user-images.githubusercontent.com/561167/118603567-5e5bc180-b7b4-11eb-8d9c-b1da980556b3.png">
<img width="1585" alt="Screenshot 2021-05-18 at 08 37 28" src="https://user-images.githubusercontent.com/561167/118603574-5ef45800-b7b4-11eb-84e4-68ec72567ae5.png">
<img width="1584" alt="Screenshot 2021-05-18 at 08 37 20" src="https://user-images.githubusercontent.com/561167/118603576-5f8cee80-b7b4-11eb-92c3-9e711af70aa5.png">
<img width="1583" alt="Screenshot 2021-05-18 at 08 37 13" src="https://user-images.githubusercontent.com/561167/118603579-60258500-b7b4-11eb-94fc-114ba80cec25.png">
<img width="1586" alt="Screenshot 2021-05-18 at 08 37 05" src="https://user-images.githubusercontent.com/561167/118603581-60258500-b7b4-11eb-9886-de85ca4a1129.png">

**Comment by stnor** [comment]
It seems to be reaching the X-Ray service, as the User filter is populated with values, and I can use these to filter traces.
But I cannot see the username when looking at/starting from a (OTEL) trace. This worked when I tried the X-Ray agent.
And is there a reason why the collector is deleting the attribute after mapping?

**Comment by anuraaga** [comment]
@stnor I believe it may be because it is only supported for rendering on a root span (Segment) rather than children (Subsegment). Are you able to add the attribute to the root instead of child?

Either way, we may need to improve the console rendering to allow the attribute on subsegments as well, there doesn't seem to be a reason not to render it.

The main reason to drop attributes that are mapped to native is to save space on what's ingested (particularly since there is a max size on a segment). We haven't heard of a need to keep them but it seems reasonable too to add an option to keep mapped attributes at the expense of space if it can be helpful.

The best would be for the X-Ray service to be updated to understand OTel attributes natively and remove the mapping altogether, but I don't think that would happen for a long time.

**Comment by stnor** [comment]
The root segments span is created by the OTEL Agent auto instrumentationfor Tomcat I believe, so I don't think so?
How would I do that?

I have some suggestions on dropping stuff if you want to save space :)

```
{
    "default": {
        "otel.resource.telemetry.sdk.name": "opentelemetry",
        "otel.resource.process.runtime.description": "Amazon.com Inc. OpenJDK 64-Bit Server VM 11.0.11+9-LTS",
        "otel.resource.process.runtime.version": "11.0.11+9-LTS",
        "otel.resource.process.command_line": "/usr/lib/jvm/java-11-amazon-corretto:bin:java --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Djava.util.logging.config.file=/opt/nomp/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -javaagent:/opt/aws-opentelemetry-agent-1.1.0-nomp.jar -Dotel.resource.attributes=service.name=Nomp -Dotel.instrumentation.jedis.enabled=false -Dotel.instrumentation.spring-web.enabled=false -Dotel.traces.sampler=nomp -Denv=prod -Dfile.encoding=utf8 -Dnomp.loglevel=INFO -XX:+AlwaysPreTouch -Xms2500m -Xmx2500m -XX:MetaspaceSize=200m -XX:MaxMetaspaceSize=250m -XX:+DisableExplicitGC -XX:-OmitStackTraceInFastThrow -XX:+UseCompressedOops -XX:+UseG1GC -XX:ParallelGCThreads=3 -XX:ConcGCThreads=2 -XX:+UseStringDeduplication -XX:+UnlockDiagnosticVMOptions -Djava.security.egd=file:/dev/urandom -Djava.locale.providers=COMPAT,CLDR,SPI -DWEB_SOCKET_DISABLED=false -Dorg.opensaml.httpclient.https.disableHostnameVerification=true -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -Dcatalina.base=/opt/nomp -Dcatalina.home=/opt/nomp -Djava.io.tmpdir=/opt/nomp/temp",
        "thread.name": "clientInboundChannel-2",
        "otel.resource.telemetry.auto.version": "1.1.0-nomp-aws",
        "otel.resource.process.executable.path": "/usr/lib/jvm/java-11-amazon-corretto:bin:java",
        "otel.resource.telemetry.sdk.version": "1.1.0",
        "otel.resource.os.description": "Linux 4.14.225-168.357.amzn2.x86_64",
        "otel.resource.os.type": "LINUX",
        "otel.resource.process.runtime.name": "OpenJDK Runtime Environment",
        "otel.resource.telemetry.sdk.language": "java",
        "otel.resource.cloud.provider": "aws",
    }
}

```

**Comment by anuraaga** [comment]
Ah interesting - I was going to suggest a servlet filter, but I think we may have recently changed to instrumenting Tomcat directly and it does seem like it could be difficult. Filed https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3025 to check

For attributes, OTel (not aws-otel specifically) has a philosophy of stuffing as much information as possible, and trimming down, rather than the alternate. I originally come from Zipkin with the exact opposite philosophy - don't know if I agree with it :) But given the current state, your best bet is to use the resource processor to drop unnecessary data

https://github.com/open-telemetry/opentelemetry-collector/tree/main/processor/resourceprocessor

Yes I know it sounds silly talking about a small user attribute given that :P But this is currently what we have. If you can, it'd be nice to report issues on the `opentelemetry-specification` repo for anything data model related like "too much data!", hearing directly from users will help a lot.

**Comment by anuraaga** [comment]
Ah - but we do have some options in Java too, forgot if it's easier. Something like `-Dotel.java.disabled.resource.providers=io.opentelemetry.sdk.extension.resources.ProcessResourceProvider`

https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/src/main/java/io/opentelemetry/sdk/autoconfigure/OpenTelemetrySdkAutoConfiguration.java#L79

**Comment by stnor** [comment]
I guess I can add "enduser.id2" in addition to the "enduser.id" for the time being. ;)

**Comment by stnor** [comment]
If it was up to me, I'd like to opt-in to the ```ProcessResourceProvider```. At least the static stuff.

**Comment by stnor** [comment]
See this discussion for more on the Resource attributes:
https://github.com/open-telemetry/opentelemetry-java/issues/3240

**Comment by anuraaga** [comment]
@stnor While I haven't confirmed it with code, I suspect a `ServletFilter` could actually augment the root span created by Tomcat based on https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3025. You might want to give it a try to see if we can get user onto the root span

**Comment by stnor** [comment]
I will try that. Just a question, how to I get hold of the root span from the servlet?

**Comment by anuraaga** [comment]
@stnor There's nothing special to get the root span (yet, we're thinking an API for it could be helpful in that issue). But we basically assume the filter will be run in the context of the root span, so the normal `Span.current()` should be the root (not the internal span created by a spring controller)

**Comment by stnor** [comment]
I'm getting an ApplicationSpan instance. Does that sound right?

**Comment by anuraaga** [comment]
Yeah we'd expect an `ApplicationSpan` when accessing a Span from code in your app. It's wrapping a span created by the agent and hoping that wrapped span is the one created by the Tomcat instrumentation.

**Comment by stnor** [comment]
I'll just try it out tonight CEST in prod and see if it works out as planned.

**Comment by stnor** [comment]
I didn't get the User tab to show up when clicking on the Root span in the console. I had a few filters before the OTEL filter (in order to have the Principal populated).

Is there a simple way to print the spans locally? Debug/text exporter?

**Comment by anuraaga** [comment]
@stnor Yeah `OTEL_TRACES_EXPORTER=logging`

https://github.com/open-telemetry/opentelemetry-java/tree/main/sdk-extensions/autoconfigure#logging-exporter

**Comment by stnor** [comment]
It's there, so perhaps there is a bug somewhere, as the tab doesn't show:
```
[opentelemetry.auto.trace 2021-05-20 11:25:09:840 +0200] [http-nio-8080-exec-10] INFO io.opentelemetry.exporter.logging.LoggingSpanExporter - '/api/quests' : 60a62af58b1eaac39467edef9f03b1eb e2dd0bb3e5293ac0 SERVER [tracer: io.opentelemetry.javaagent.tomcat-7.0:1.1.1-nomp-aws] AttributesMap{data={http.user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36, http.flavor=1.1, thread.id=42, enduser.id=info@nomp.se, http.client_ip=127.0.0.1, net.peer.port=64317, http.method=GET, net.peer.ip=127.0.0.1, thread.name=http-nio-8080-exec-10, http.status_code=200, http.url=http://127.0.0.1:8001/api/quests}, capacity=128, totalAddedValues=11}
```

<img width="947" alt="Screenshot 2021-05-20 at 11 28 12" src="https://user-images.githubusercontent.com/561167/118954919-871fba80-b95e-11eb-8c3c-0c3d44ea2836.png">
<img width="945" alt="Screenshot 2021-05-20 at 11 27 40" src="https://user-images.githubusercontent.com/561167/118954925-8850e780-b95e-11eb-8f69-9dfac083b86a.png">

**Comment by anuraaga** [comment]
Thanks for investigating @stnor - in general that looks like what we'd expect now, `enduser.id` on the `SERVER` span. Are you able to share the "Raw Data" JSON too? Or if you can just confirm the segment has a `user` field with that value inside it. If so, I'll ask around what other conditions may be on the mysterious user tab.

**Comment by stnor** [comment]
I'd rather not share it here. I can share it in a support ticket perhaps if you need it. The user segment is there. See this screenshot:
<img width="948" alt="Screenshot 2021-05-20 at 11 49 09" src="https://user-images.githubusercontent.com/561167/118958253-89cfdf00-b961-11eb-9886-5df8582847af.png">

**Comment by anuraaga** [comment]
@stnor Sorry for not following up. From what I heard, there's never been any special rendering of that attribute in the UI - you mentioned "This worked when I tried the X-Ray agent." but want to confirm did you actually see something in the UI?

The console team is working on adding the user field to the Overview tab so it will show up after that gets pushed out at some point.

**Comment by stnor** [comment]
I might be mistaken, it was a while back:

Found this trace from May 1st. Didn't show the user tab (now anyway).

```
               "aws": {
                    "xray": {
                        "sdk_version": "2.9.0",
                        "sdk": "X-Ray for Java"
                    }
                },
                "service": {
                    "runtime": "OpenJDK 64-Bit Server VM",
                    "runtime_version": "15.0.2"
                },
                "user": "demo1"

```

**Comment by stnor** [comment]
> From what I heard, there's never been any special rendering of that attribute in the UI - you mentioned "This worked when I tried the X-Ray agent."

Ok, so the workaround for now would be to log the username in another attribute in addition to enduser.id?

**Comment by anuraaga** [comment]
To see it in the console right now I think that is the best way indeed. X-Ray really shouldn't define any structured fields that aren't rendered so will follow up on whether there's anything else missing.
