### ISSUE TITLE
[ci] Add new EKS cluster targets

### ISSUE THREAD

**Issue by bryan-aguilar** [aws-observability/aws-otel-java-instrumentation#570]
https://github.com/aws-observability/aws-otel-test-framework/pull/1447 deployed EKS clusters for v1.24 - v1.27. 

The Java Agent [testcases](https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/.github/workflows/testcases.json) file needs to be updated for these new clusters. 

New clusters
```
java-instrumentation-operator-ci-amd64-1-24
java-instrumentation-operator-ci-arm64-1-24
java-instrumentation-operator-ci-amd64-1-27
java-instrumentation-operator-ci-arm64-1-27
```

```[tasklist]
### Add new cluster steps
- [x] Test new clusters by adding them to target list
- [x] Remove old clusters
```

**Comment by PaurushGarg** [comment]
Closing issue as relevant PR has been merged.
