### ISSUE TITLE
Performance/Throughput Impact with auto instrumentation in Spring 5 applications

### ISSUE THREAD

**Issue by kurvatch** [aws-observability/aws-otel-java-instrumentation#59]
**Describe the bug**
We are seeing more than 50% performance degradation with instrumenting otel agents, Our application instrumented with otel runs on EKS cluster. OTel Collector running as daemon set in the same EKS cluster collects traces and ingest data to AWS Xray.

**Steps to reproduce**
This is Spring 5 project with webflux and spring cloud stream support interacting with SQS, DynamoDB and AWS MSK

**What did you expect to see?**
Without Otel Agent, application could reach upto 250 request per second with 2Gi memory.

**What did you see instead?**
After OTel agent, we are seeing ~65 request per second with same settings, I was expecting some degradation in the throughput but this is more 50%

**Additional context**
We are using aws-opentelemetry-agent-1.1.0 with default settings for BSP and sampling is set to 100% and metrics exporter is set to logging.

**Comment by stnor** [comment]
What tracer are you using? Trace ratio?

**Comment by kurvatch** [comment]
@stnor `parentbased_always_on` is the sampler. I am testing things out with default configurations, it was expected there will be a performance impact with 100% sampling but was shocked to see more than 70% degradation of throughput. I am doing another round of testing with `parentbased_traceidratio` and '-Dotel.traces.sampler.arg=0.25' for the same application.

**Comment by stnor** [comment]
25% in an very high sampling frequency in my experience.

**Comment by kurvatch** [comment]
Is there a standards recommendation available. It would defiantly help to publish benchmark performance with different samplers and ratios with a demo application interacting database and a message system

**Comment by anuraaga** [comment]
Hi @kurvatch - I agree that the performance impact seems much larger than we'd expect. Sampling rate is great for reducing load on backends, but we wouldn't expect such that much overhead at hundreds of QPS. 

I have filed https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3047 as that repo is where the actual code is and the performance bottlenecks can be investigated.
