### ISSUE TITLE
Repackage OpenTelemetry Java Agent to 1.4.0

### ISSUE THREAD

**Issue by HashemTaheriSonos** [aws-observability/aws-otel-java-instrumentation#63]
Any estimation about when are we going to have the base otel agent updated? 
currently, it's based on v1.2.0 which includes the [out-of-memory](https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/3059) issue.

That problem got solved in otel agent [v1.3.0 ](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.3.0)(1) but the PR and the merge for upgrading the agent failed in here;

recently, [v1.4.0](https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v1.4.0) has been released, so looking forward to this one :)

Thanks in advance

**Comment by anuraaga** [comment]
Thanks @HashemTaheriSonos - we had to skip 1.3 for this distro since support for metrics was broken in it, we will try to release a 1.4 soon

**Comment by HashemTaheriSonos** [comment]
Thanks, @anuraaga for the quick PR for upgrading, however, I see this time the merge was successful but it got failed at the [building/publishing stage](https://github.com/aws-observability/aws-otel-java-instrumentation/runs/3120341020?check_suite_focus=true).

**Comment by anuraaga** [comment]
That is a different build to check whether we will have to address breaking changes on the next release. The main build is green! So we will be able to release soon.

**Comment by HashemTaheriSonos** [comment]
oh Okk, I see... cool, looking forward to it ✌️

**Comment by anuraaga** [comment]
@HashemTaheriSonos - Thanks for the patience. 1.4.0 has been released, hope it works well for you.
