### ISSUE TITLE
Not logging trace id after AWS Auto Instrumentation Agent upgrade to 1.2.0 or 1.4.0

### ISSUE THREAD

**Issue by drazzi-lee** [aws-observability/aws-otel-java-instrumentation#66]
**Describe the bug**
We are tracing our SpringBoot/SpringCloudGateway application by the AWS Auto Instrumentation Agent. After I change the release from Release v1.1.0 to Release v1.4.0, the traceId shows empty, and the key AWS-XRAY-TRACE-ID in MDC context map has also disappeared.

**Steps to reproduce**
`java -Dspring.profiles.active=local -javaagent:/aotel/aws-opentelemetry-agent-1.4.0.jar one.jar`
"one.jar" is a SpringBoot application, configuring by logback pattern:
`%d{yyyy-MM-dd HH:mm:ss.SSS}\t[%X{AWS-XRAY-TRACE-ID}] - %msg%n`

**What did you expect to see?**
Before upgrade, using agent 1.1.0:
`java -Dspring.profiles.active=local -javaagent:/aotel/aws-opentelemetry-agent-1.1.0.jar one.jar`
the log is showing like this:
`2021-07-29 18:50:09.618  [1-610287e1-4bad020c021ab9b074d04217@a01edea91aca582c] origin request body: ...`

**What did you see instead?**
After upgrade to agent 1.2.0 or 1.4.0, logging like this:
`2021-07-29 18:50:09.618  [] origin request body: ...`
There are none AWS-XRAY-TRACE-ID in MDC context by debug mode: 
`  "mdc": {
    "appVersion": "",
    "interface io.opentelemetry.javaagent.shaded.io.opentelemetry.api.trace.Span": "{opentelemetry-trace-span-key=RecordEventsReadableSpan{traceId=610399e3815dc59e58765f785125a19c, spanId=52817ef4208de551, parentSpanContext=ImmutableSpanContext{traceId=610399e3815dc59e58765f785125a19c, spanId=0877b939030ee172, traceFlags=01, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=true}, name=FilteringWebHandler.handle, kind=INTERNAL, attributes=AttributesMap{data={thread.name=reactor-http-nio-4, thread.id=43}, capacity=128, totalAddedValues=2}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1627625955919426700, endEpochNanos=0}, opentelemetry-traces-server-span-key=RecordEventsReadableSpan{traceId=610399e3815dc59e58765f785125a19c, spanId=0877b939030ee172, parentSpanContext=ImmutableSpanContext{traceId=00000000000000000000000000000000, spanId=0000000000000000, traceFlags=00, traceState=ArrayBasedTraceState{entries=[]}, remote=false, valid=false}, name=HTTP POST, kind=SERVER, attributes=AttributesMap{data={net.peer.port=51264, schoolCode=415, http.method=POST, clientType=, http.user_agent=PostmanRuntime/7.28.2, platformVersion=, http.url=http://localhost:8080/v1/aggregate/user/info, platform=, studentId=7592518, http.client_ip=0:0:0:0:0:0:0:1, net.peer.ip=0:0:0:0:0:0:0:1, thread.name=reactor-http-nio-4, deviceName=, appVersion=, thread.id=43, http.flavor=1.1, appName=}, capacity=128, totalAddedValues=17}, status=ImmutableStatusData{statusCode=UNSET, description=}, totalRecordedEvents=0, totalRecordedLinks=0, startEpochNanos=1627625955919001800, endEpochNanos=0}}",
    "appName": "",
    "requestMethod": "POST",
    "reactor.onDiscard.local": "reactor.core.publisher.Operators$$Lambda$1192/593986789@222b5946",
    "requestUri": "/v1/aggregate/user/info",
    "deviceName": "",
    "platform": "",
    "studentId": "7592518",
    "hostname": "ZT-081201",
    "clientType": "",
    "platformVersion": "",
    "schoolCode": "415",
    "remoteAddr": "0:0:0:0:0:0:0:1",
    "trace_id": "610399e3815dc59e58765f785125a19c",
    "trace_flags": "01",
    "span_id": "0877b939030ee172"
  },`

I don’t know where the usage has changed, or there is a bug here, any suggestions or code would be appreciated.

**Comment by anuraaga** [comment]
@drazzi-lee Thanks for filing this issue - this seems to be a bug, we will fix and issue a patch soon

**Comment by anuraaga** [comment]
@drazzi-lee 1.4.1 has been released and should propagate through Maven Central shortly, containing the fix for this. Thanks again for reporting!
