### ISSUE TITLE
Feature Request: Centralized sampling for "AWS Distro for OpenTelemetry" SDK

### ISSUE THREAD

**Issue by TheRealGoku** [aws-observability/aws-otel-java-instrumentation#69]
The request is to support sampling logic in ADOT sdk as similar like what has been currently offered in X-Ray SDK.

**Comment by anuraaga** [comment]
Thanks @TheRealGoku - we're aiming to get this published soon for use as a preview feature. Stay tuned.

**Comment by stefanorg** [comment]
Hi, any update on this?

**Comment by anuraaga** [comment]
@stefanorg We're currently working on adding support for the sampling API proxy to the collector but it's taking some time due to how busy the collector repo is.

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4625

**Comment by awsiv** [comment]
@anuraaga After this PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4625, is there anything remaining for this to be usable?

**Comment by anuraaga** [comment]
This has been released in 1.7, with important fixes in 1.9, so closing - happy sampling!
