### ISSUE TITLE
Unable to see OpenTelemetry Span Events in AWS X-Ray

### ISSUE THREAD

**Issue by rcooper85** [aws-observability/aws-otel-java-instrumentation#73]
**Describe the bug**
When trying to add a [Span Event](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#add-events) to a span using the span.current.addEvent() method in OpenTelemetry, the event is not visible in AWS X-Ray. We can see our custom spans but none of the Events.  
**Steps to reproduce**
We are using a Java SpringBoot application using the spring-boot-starter-parent version 2.4.5. We are using the opentelemetry-otlp-exporter-starter 1.4.1-alpha dependency. 

We created a docker image for our application that adds the aws-opentelemetry-agent.jar (v1.4.1) into the image when we build it. We then run as a javaagent when the image is deployed. We deploy our application to ECS Fargate and we then run the aws-otel-collector as a sidecar with the default configuration. 

**What did you expect to see?**
We expected to see our span events either as annotations or metadata in our spans. 

**What did you see instead?**
We just saw our custom spans without any Span Events. 

**Additional context**
We are also experiencing the same behaviour when we use Elastic as the backend for observability. This is due to this [issue](https://github.com/elastic/apm-server/issues/4715)

**Comment by anuraaga** [comment]
Thanks for filing this @rcooper85 - indeed similar to Elastic, the X-Ray data model itself doesn't contain the concept of events so supporting them will be a big change including the backend. Events can be pretty interesting so hopefully we can add support for them but it will take some time.

**Comment by rcooper85** [comment]
Hi @anuraaga - thank you for your quick response on this. Is that the same for `setStatus` for spans too? As we are not seeing the status in X-Ray either when we use, for example:  `Span.current().setStatus(StatusCode.OK, "Order Received");`
