### ISSUE TITLE
Version 1.5.0 throws NoSuchMethodError

### ISSUE THREAD

**Issue by otbe** [aws-observability/aws-otel-java-instrumentation#77]
**Describe the bug**
We updated from 1.4.1 of the AWS flavoured agent to 1.5.0 and start to see exceptions in the log like this

```
Caused by: java.lang.NoSuchMethodError: 'io.opentelemetry.sdk.resources.Resource io.opentelemetry.sdk.autoconfigure.OpenTelemetrySdkAutoConfiguration.getResource()'
--
  |   | at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
  |   | at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
  |   | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  |   | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  |   | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  |   | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  |   | at software.amazon.opentelemetry.javaagent.bootstrap.AwsAgentBootstrap.premain(AwsAgentBootstrap.java:24)
  |   | at software.amazon.opentelemetry.javaagent.bootstrap.AwsAgentBootstrap.agentmain(AwsAgentBootstrap.java:28)
  |   | at io.opentelemetry.javaagent.OpenTelemetryAgent.agentmain(OpenTelemetryAgent.java:51)
  |   | at io.opentelemetry.javaagent.bootstrap.AgentInitializer.initialize(AgentInitializer.java:40)
  |   | at java.base/java.lang.reflect.Method.invoke(Method.java:566)
  |   | at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  |   | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  |   | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

```

**Additional context**
We also updated the opentelemtry bom version to 1.5.0 as suggested but we're only using the aws extensions for injecting the trace ID into our HTTP responses.

Any ideas whats going on?
Our application works great with aws agent 1.4.1 and open telemetry 1.4.0

**Comment by anuraaga** [comment]
Hi @otbe - can you describe any env vars or properties you set when running? Or if you use any custom extensions?

That stack trace seems like it would be easy to repro but our integration tests that simply export OTLP seem to be ok so wonder if it's specific to a particular setting.

**Comment by otbe** [comment]
We use the following cmd line args:
`/usr/bin/java -XX:MaxRAMPercentage=50 -javaagent:/home/service/aws-opentelemetry-agent.jar -XX:OnOutOfMemoryError="/home/service/oom_alert.sh" -jar -Djava.security.egd=file:/dev/./urandom /home/service/service.jar`

And these are the env vars related to adot/opentelemtry:
```
- Name: OTEL_RESOURCE_ATTRIBUTES
  Value: service.name=my-funny-service
- Name: OTEL_EXPORTER_OTLP_ENDPOINT
  Value: http://localhost:55680
- Name: OTEL_TRACES_SAMPLER
  Value: parentbased_traceidratio
- Name: OTEL_TRACES_SAMPLER_ARG
  Value: '0.05'
- Name: OTEL_METRICS_EXPORTER
  Value: none
```

**Comment by anuraaga** [comment]
Thanks @otbe - I think I found the culprit and it will need a patch. It is triggered by the presence of `OTEL_TRACES_SAMPLER`. I'm still not sure why our integration test with that flag is not failing, it should be

https://github.com/aws-observability/aws-otel-java-instrumentation/blob/main/smoke-tests/runner/src/test/java/io/awsobservability/instrumentation/smoketests/runner/SpringBootSmokeTest.java#L135

But will try to get the patch out shortly.

**Comment by anuraaga** [comment]
@otbe 1.5.1 has been released, can you give it a try?

**Comment by otbe** [comment]
@anuraaga 1.5.1 works! 
Thanks

**Comment by anuraaga** [comment]
Great, thanks for verifying @otbe!
