### ISSUE TITLE
[OTel SDKs] Automated performance test for OTel SDK to identify SDK performance, CPU and memory bottlenecks.

### ISSUE THREAD

**Issue by bhautikpip** [aws-observability/aws-otel-java-instrumentation#9]
Automated performance test workflow for AWS OTel Java agent

1. Build automated performance test using benchmarking
2. performance test should be run weekly basis 
3. should be able to identify CPU, memory bottlenecks as well as gives insights on API response time and SDK API bottlenecks

**Comment by anuraaga** [comment]
Is there anything unique to do here or can we implement this upstream? Even if we want to swap out the agent we publish, I think we should implement this upstream and reuse.

**Comment by bhautikpip** [comment]
Submitted latency benchmark PR (upstream) - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/1935
