### ISSUE TITLE
aws-otel-java-instrumentation : aws-xray not showing connected traces with kafka

### ISSUE THREAD

**Issue by saumya2700** [aws-observability/aws-otel-java-instrumentation#96]
**Describe the bug**
spring java applications have kafka implementation, one is producing message and other is consuming, running it with aws opentelemetry javaagent, collector is installed , traces are generated and I can see on aws-xray console but producer-consumer  graph and traces are not connected.

When I printed headers I can see AWS-Amazon-Xray-Id header in both producer and consumer. Trace id value is same in this header but trace-id is different when printing it in logs.

e.g : TRACES from my application

9090] 2021-10-07 18:49:18 - c.n.n.k.i.KafkaProducerInterceptor - HEADERS IN PRODUCER**-----for TOPIC XXXX , {traceparent=00-615ef3d419ea6e5838f81274b50e4dde-8816e8faeacd8c8a-01, **X-Amzn-Trace-Id=Root=1-615ef3d4-19ea6e5838f81274b50e4dde**;Parent=8816e8faeacd8c8a;Sampled=1} **trace_id**=615ef3d419ea6e5838f81274b50e4dde span_id=8816e8faeacd8c8a trace_flags=01

[9090] 2021-10-07 18:49:18 - c.n.n.k.i.KafkaConsumerInterceptor - HEADERS IN CONSUMER-----for TOPIC XXXX , {nn-api-key-id=null, nn-timestamp=null, traceparent=00-615ef3d419ea6e5838f81274b50e4dde-8816e8faeacd8c8a-01, nn-app-name=null, nn-device-id=null, **X-Amzn-Trace-Id=Root=1-615ef3d4-19ea6e5838f81274b50e4dde**;Parent=8816e8faeacd8c8a;Sampled=1, nn-trans-id=9090} **trace_id**=615ef3d63e20955caaa62e7a3bd423e9 span_id=1633f0c818ad6cf1 trace_flags=01

**Steps to reproduce**
two microservices , getting request and sending message to kafka, other microservice is consuming the same message on same topic.

**What did you expect to see?**
from controller to producer and also consumer traces should be connected on aws-xray-console

**What did you see instead?**
1. One set of traces for controller to producer
2. then other set of traces with different trace-id

**Additional context**
I have tested in two sets of application, result is same not connecting:
1. two microservices have simple kafka implementation
2. Another two microservices have kafka and kafka streams implementation and also have Spring's DeferredResult

**Comment by saumya2700** [comment]
Hi @anuraaga ,
It worked, I tried with 1.7.0 and Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true and from local I can see traces are connected.
Thank you for your support.

**Comment by anuraaga** [comment]
Thanks for confirming!

**Comment by sukrit007** [comment]
Hello, I am still getting this issue.  I am using

- Spring Kafka 2.7
- `otel.resource.process.command_line": "/usr/lib/jvm/java-11-openjdk:bin:java -javaagent:/work/aws-opentelemetry-agent.jar 
    -Djava.awt.headless=true -Djava.awt.headless=true -Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true`
-  AWS  OTel Java Instrumentation - 1.9.0
-  AWS OTel Collector : amazon/aws-otel-collector:v0.15.1

It looks like traceId is not propagated and XRay shows new traceId
